services:
    frontend:
        restart: always
        container_name: frontend
        build: ./frontend
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    backend:
        restart: always
        container_name: backend
        build: ./server
        volumes:
            - './server:/server'
            - '/server/node_modules'
        ports:
            - 4000:4000
    database:
        restart: always
        image: mariadb:10.5.8
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: testing
        ports:
            - 3306:3306
        volumes:
            - './database-data:/var/lib/mysql'
volumes:
    database-data:
