services:
    frontend:
        container_name: frontend
        build: ./frontend
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    backend:
        container_name: backend
        build: ./server
        volumes:
            - './server:/server'
            - '/server/node_modules'
        ports:
            - 4000:4000
